apiVersion: v1
kind: ConfigMap
metadata:
  name: etf-overlap-config
  namespace: etf-overlap
data:
  POSTGRES_DB: "etf_overlap"
  POSTGRES_USER: "postgres"
  NODE_ENV: "production"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
  PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"
