apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etf-overlap

resources:
  - namespace.yaml
  - app-deployment.yaml
  - app-service.yaml
  - ingress.yaml

# Configure image for the app
images:
  - name: etf-overlap
    newName: registry.whiterabbit.co.kr/apps/etf-overlap
    newTag: latest
